import storage.DatabaseInitService;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        //Init DB using flyway
        new DatabaseInitService().initDb();
    }
}
